include:
  - path: trypto-infra/docker-compose.yml
  - path: trypto-collector/docker-compose.yml
  - path: trypto-api/docker-compose.yml
  - path: trypto-engine/docker-compose.yml
  - path: trypto-compensation/docker-compose.yml
